from sqlalchemy import Column, Integer, String, Text, ForeignKey, JSON, Float
from sqlalchemy.orm import relationship
from .database import Base


# ============================================================
# MEETING
# ============================================================
class Meeting(Base):
    __tablename__ = "meetings"

    meeting_id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # Core metadata
    date = Column(String(50), nullable=True)
    type = Column(String(200), nullable=True)

    # Optional metadata
    url = Column(String(500), nullable=True)
    agenda_pdf_url = Column(String(500), nullable=True)
    accessible_pdf_url = Column(String(500), nullable=True)

    raw_text = Column(Text, nullable=True)
    processed_summary = Column(Text, nullable=True)  # meeting-level summary (future)

    # Relationship: ONE meeting → MANY items
    items = relationship("Item", back_populates="meeting")



# ============================================================
# ITEM
# ============================================================
class Item(Base):
    __tablename__ = "items"

    item_id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    meeting_id = Column(Integer, ForeignKey("meetings.meeting_id"), nullable=False)

    # Agenda structure
    section_code = Column(String(10), nullable=True)
    section_title = Column(String(200), nullable=True)

    # Core item info
    item_title = Column(String(500), nullable=True)
    case_code = Column(String(100), nullable=True)
    description = Column(Text, nullable=True)

    # Extracted civic info
    location = Column(String(500), nullable=True)
    presenters = Column(JSON, default=lambda: [])
    raw_block = Column(Text, nullable=True)

    # NLP / ML fields
    topics_detected = Column(JSON, default=lambda: [])
    locations_detected = Column(JSON, default=lambda: [])
    embedding_vector = Column(JSON, default=None)

    # Summary generated by LLM
    processed_summary = Column(Text, nullable=True)

    # Relationship
    meeting = relationship("Meeting", back_populates="items")



# ============================================================
# USER
# ============================================================
class User(Base):
    __tablename__ = "users"

    user_id = Column(Integer, primary_key=True, index=True)

    email = Column(String, unique=True, nullable=False)
    interested_topics = Column(JSON, default=list)

    # Legacy single-area fields (optional)
    address = Column(String(500), nullable=True)
    buffer_radius = Column(Integer, default=5)

    # Relationship: ONE user → MANY area subscriptions
    locations = relationship("UserLocation", back_populates="user", cascade="all, delete")



# ============================================================
# USER LOCATIONS (Multiple areas user cares about)
# ============================================================
class UserLocation(Base):
    __tablename__ = "user_locations"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)

    user_id = Column(Integer, ForeignKey("users.user_id"), nullable=False)

    # Label (e.g., "Home", "Work", "North Intersection")
    label = Column(String(200), nullable=True)

    # Original user-entered address
    address = Column(String(500), nullable=False)

    # Normalized address (from geocoder)
    normalized_address = Column(String(500), nullable=True)

    # Geocoded coordinates
    lat = Column(Float, nullable=True)
    lon = Column(Float, nullable=True)

    # Search radius for this area
    radius_miles = Column(Float, nullable=False, default=5.0)

    user = relationship("User", back_populates="locations")

class GeocodeCache(Base):
    __tablename__ = "geocode_cache"

    address = Column(String(500), primary_key=True)
    lat = Column(String(50), nullable=False)
    lon = Column(String(50), nullable=False)
